services:
  - xvfb
language: python
python: 2.7
cache:
  directories:
  - eggs
  - parts/node
env:
  global:
  - PLONE_CSRF_DISABLED=true
  matrix:
  # TODO: update https://github.com/plonegovbr/portalpadrao.release/blob/master/README.md
  - DEVELOPMENT=true
  - PRODUCTION=true
matrix:
  allow_failures:
  - env: PRODUCTION=true
  fast_finish: true
before_install:
  - GECKODRIVER_VERSION=0.26.0
  - wget https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
  - sudo tar -xzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz -C /usr/bin
  - firefox -v
  - test $DEVELOPMENT && cp travis-development.cfg buildout.cfg || cp travis-production.cfg buildout.cfg
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/buildout annotate
  - bin/buildout
  # O release 1.1.5.1 veio com um erro e não vinha com os eggs do brasil.gov.portal.
  # Dessa forma, passamos a testar se o egg foi realmente adicionado no buildout
  # para que esse erro não ocorra novamente.
  # Caso altere a versão do zc.buildout, pode ser que você necessite alterar o
  # arquivo onde procura a string, trocando bin/instance por parts/instance.site.py
  # por exemplo.
  - grep -q 'brasil.gov.portal' bin/instance
script:
# FIXME: we have isolation issues running tests
- bin/test -s brasil.gov.agenda &&
  bin/test -s brasil.gov.barra &&
  bin/test -s brasil.gov.portal &&
  bin/test -s brasil.gov.portlets &&
  bin/test -s brasil.gov.temas &&
  bin/test -s brasil.gov.tiles &&
  bin/test -s brasil.gov.vcge
after_failure:
- grep brasil.gov bin/test
notifications:
  irc: irc.freenode.org#plonegovbr
